CREATE TABLE cases (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    case_number VARCHAR(100) NOT NULL UNIQUE,
    fir_number VARCHAR(100),
    police_station VARCHAR(255),
    offence_section VARCHAR(100) NOT NULL,
    offence_type VARCHAR(100),
    maximum_sentence_years INT,
    custody_start_date DATE,
    first_time_offender BOOLEAN DEFAULT TRUE,
    residential_stability BOOLEAN DEFAULT TRUE,
    employment_status VARCHAR(100),
    dependents INT DEFAULT 0,
    previous_court_appearances INT DEFAULT 0,
    previous_absconding BOOLEAN DEFAULT FALSE,
    witness_tampering BOOLEAN DEFAULT FALSE,
    co_accused BOOLEAN DEFAULT FALSE,
    evidence_type VARCHAR(100),
    case_stage VARCHAR(100),
    surety_available BOOLEAN DEFAULT TRUE,
    bond_ready BOOLEAN DEFAULT TRUE,
    identification_ready BOOLEAN DEFAULT TRUE,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    created_by_id VARCHAR(36) NOT NULL,
    organization_id VARCHAR(36),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT fk_cases_created_by FOREIGN KEY (created_by_id) REFERENCES users (id),
    CONSTRAINT fk_cases_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
