-- Seed More Penal Codes & Procedural Sections (IPC, BNS, CrPC, BNSS)
INSERT INTO law_sections (id, law_name, section_number, title, description, plain_language_summary, bailable, maximum_sentence_years, ipc_equivalent, bns_equivalent, crpc_equivalent, bnss_equivalent, source, repository_version, verified_at, active)
VALUES
('55555555-1111-1111-1111-304111111111', 'Indian Penal Code', '304A', 'Causing death by negligence', 'Whoever causes the death of any person by doing any rash or negligent act not amounting to culpable homicide, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.', 'Causing death due to rash or negligent driving or action. Statutory bailable offence carrying up to 2 years imprisonment.', TRUE, 2, 'IPC 304A', 'BNS 106', 'CrPC 436', 'BNSS 478', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-307111111111', 'Indian Penal Code', '307', 'Attempt to murder', 'Whoever does any act with such intention or knowledge, and under such circumstances that, if he by that act caused death, he would be guilty of murder, shall be punished with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.', 'Severe offence involving attempt to cause death. Non-bailable offence carrying up to 10 years or life imprisonment.', FALSE, 10, 'IPC 307', 'BNS 109', 'CrPC 437', 'BNSS 479', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-323111111111', 'Indian Penal Code', '323', 'Punishment for voluntarily causing hurt', 'Whoever, except in the case provided for by section 334, voluntarily causes hurt, shall be punished with imprisonment of either description for a term which may extend to one year, or with fine which may extend to one thousand rupees, or with both.', 'Simple assault or physical hurt. Statutory bailable offence carrying up to 1 year imprisonment.', TRUE, 1, 'IPC 323', 'BNS 115', 'CrPC 436', 'BNSS 478', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-325111111111', 'Indian Penal Code', '325', 'Punishment for voluntarily causing grievous hurt', 'Whoever, except in the case provided for by section 335, voluntarily causes grievous hurt, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.', 'Inflicting serious bodily injuries or fractures. Statutory bailable offence carrying up to 7 years imprisonment.', TRUE, 7, 'IPC 325', 'BNS 117', 'CrPC 436', 'BNSS 478', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-354111111111', 'Indian Penal Code', '354', 'Assault or criminal force to woman with intent to outrage her modesty', 'Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished with imprisonment of either description for a term which shall not be less than one year but which may extend to five years, and shall also be liable to fine.', 'Offence against modesty of a woman. Non-bailable classification requiring judicial evaluation.', FALSE, 5, 'IPC 354', 'BNS 74', 'CrPC 437', 'BNSS 479', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-380111111111', 'Indian Penal Code', '380', 'Theft in dwelling house, etc.', 'Whoever commits theft in any building, tent or vessel, which building, tent or vessel is used as a human dwelling, or used for the custody of property, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.', 'Theft committed inside residential premises or storehouses. Non-bailable offence carrying up to 7 years imprisonment.', FALSE, 7, 'IPC 380', 'BNS 305', 'CrPC 437', 'BNSS 479', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-384111111111', 'Indian Penal Code', '384', 'Punishment for extortion', 'Whoever commits extortion shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.', 'Coercing or blackmailing property under threat of harm. Non-bailable offence carrying up to 3 years imprisonment.', FALSE, 3, 'IPC 384', 'BNS 308', 'CrPC 437', 'BNSS 479', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-406111111111', 'Indian Penal Code', '406', 'Punishment for criminal breach of trust', 'Whoever commits criminal breach of trust shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.', 'Misappropriating entrusted property or funds. Non-bailable offence carrying up to 3 years imprisonment.', FALSE, 3, 'IPC 406', 'BNS 316', 'CrPC 437', 'BNSS 479', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-411111111111', 'Indian Penal Code', '411', 'Dishonestly receiving stolen property', 'Whoever dishonestly receives or retains any stolen property, knowing or having reason to believe the same to be stolen property, shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.', 'Possession or receipt of stolen goods. Non-bailable offence carrying up to 3 years imprisonment.', FALSE, 3, 'IPC 411', 'BNS 317', 'CrPC 437', 'BNSS 479', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-436111111111', 'Code of Criminal Procedure', '436', 'In what cases bail to be taken', 'When any person other than a person accused of a non-bailable offence is arrested or detained without warrant by an officer in charge of a police station, or appears or is brought before a Court, and is prepared at any time while in the custody of such officer or at any stage of the proceeding before such Court to give bail, such person shall be released on bail.', 'Mandatory statutory right to bail in all bailable offences upon executing personal bond or surety.', TRUE, 0, 'CrPC 436', 'BNSS 478', 'CrPC 436', 'BNSS 478', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-436A11111111', 'Code of Criminal Procedure', '436A', 'Maximum period for which an undertrial prisoner can be detained', 'Where a person has, during the period of investigation, inquiry or trial under this Code of an offence under any law (not being an offence for which the punishment of death has been specified as one of the punishments under that law) undergone detention for a period extending up to one-half of the maximum period of imprisonment specified for that offence under that law, he shall be released by the Court on his personal bond with or without sureties.', 'Mandatory statutory discharge/bail for undertrials who have served 1/2nd (or 1/3rd for first-time offenders) of maximum imprisonment term.', TRUE, 0, 'CrPC 436A', 'BNSS 479', 'CrPC 436A', 'BNSS 479', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-468111111111', 'Indian Penal Code', '468', 'Forgery for purpose of cheating', 'Whoever commits forgery, intending that the document or electronic record forged shall be used for the purpose of cheating, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.', 'Forging documents or records to deceive or defraud. Non-bailable carrying up to 7 years imprisonment.', FALSE, 7, 'IPC 468', 'BNS 336', 'CrPC 437', 'BNSS 479', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-498111111111', 'Indian Penal Code', '498A', 'Husband or relative of husband of a woman subjecting her to cruelty', 'Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine.', 'Domestic cruelty against a woman by husband or in-laws. Non-bailable classification requiring Arnesh Kumar compliance.', FALSE, 3, 'IPC 498A', 'BNS 85', 'CrPC 437', 'BNSS 479', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE),

('55555555-1111-1111-1111-506111111111', 'Indian Penal Code', '506', 'Punishment for criminal intimidation', 'Whoever commits the offence of criminal intimidation shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.', 'Threatening another person with injury or harm. Statutory bailable offence carrying up to 2 years imprisonment.', TRUE, 2, 'IPC 506', 'BNS 351', 'CrPC 436', 'BNSS 478', 'STATUTORY REPOSITORY v2.0', 'v2.0-OFFICIAL', NOW(), TRUE);
