import React from 'react'
import { Scale, HeartHandshake, ShieldCheck } from 'lucide-react'

export const Footer: React.FC = () => {
  return (
    <footer className="bg-white border-t border-surface-deep mt-auto py-8 text-xs text-ink-muted">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4 border-b border-surface-deep pb-6">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-accent text-white flex items-center justify-center">
              <Scale className="w-5 h-5" />
            </div>
            <div>
              <span className="font-serif font-bold text-base text-ink block">Bail Reckoner</span>
              <span className="text-[10px] font-mono text-ink-muted">Digital Legal-Aid Decision Support System</span>
            </div>
          </div>

          <div className="flex items-center gap-6 text-xs">
            <span className="flex items-center gap-1 text-ink">
              <ShieldCheck className="w-4 h-4 text-emerald-600" /> WCAG 2.1 AA Compliant
            </span>
            <span className="flex items-center gap-1 text-ink">
              <HeartHandshake className="w-4 h-4 text-accent" /> Public Service Legal Aid
            </span>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 leading-relaxed">
          <div>
            <strong className="text-ink font-semibold block mb-1">Legal Aid Notice:</strong>
            <p>
              Bail Reckoner is designed for legal-aid lawyers, undertrial prisoners, families, and NGO volunteers to evaluate undertrial custody duration and bailability under Indian statutory provisions (IPC, BNS, CrPC, BNSS).
            </p>
          </div>
          <div>
            <strong className="text-ink font-semibold block mb-1">Authoritative Rule Disclaimer:</strong>
            <p>
              Assessments generated by this system are produced by a deterministic statutory rule engine. This system provides decision assistance and does not replace formal judicial proceedings or professional legal representation.
            </p>
          </div>
        </div>

        <div className="text-center pt-2 text-[11px] border-t border-surface-light">
          © {new Date().getFullYear()} Bail Reckoner Project • Built for Public Good & Judicial Accessibility
        </div>
      </div>
    </footer>
  )
}
